language: elixir

elixir:
  - 1.4.2

otp_release:
  - 19.2

sudo: required

services:
  - docker

script:
  - mix test --trace

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "Building container gonitro/spacesuit:${TRAVIS_COMMIT::7}";
      docker/build.sh;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ -z "${NO_PUSH_LATEST}" ]; then
      docker push gonitro/spacesuit:latest;
    fi
