language: elixir

elixir:
  - 1.4.2

otp_release:
  - 19.2

sudo: required

services:
  - docker

script:
  - mix test
  - echo "Building container gonitro/spacesuit:${TRAVIS_COMMIT::7}" && docker/build.sh
