---
":_":
   "/users/:user_id":
     name: "users to localhost:9090"
     map: "http://localhost:9090/:user_id"

   "/[...]":
     name: "others to hacker news"
     destination: "https://news.ycombinator.com"
