---
":_":
   "/users/:user_id":
     description: "users to localhost:9090"
     map: "http://localhost:9090/:user_id"

   "/users/something/:user_id":
     description: "users to localhost:9090"
     map: "http://localhost:9090/something/:user_id"

   "/[...]":
     description: "others to hacker news"
     destination: "https://news.ycombinator.com"
